//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Runtime"",
            ""id"": ""870e509e-499f-4bd5-87f2-7dd51fb06be8"",
            ""actions"": [
                {
                    ""name"": ""TestAudio"",
                    ""type"": ""Button"",
                    ""id"": ""4463e7c2-825c-47f2-9251-6cfc4b156810"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""19e50893-014f-437a-adac-994f397af092"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestAudio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Runtime
        m_Runtime = asset.FindActionMap("Runtime", throwIfNotFound: true);
        m_Runtime_TestAudio = m_Runtime.FindAction("TestAudio", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Runtime
    private readonly InputActionMap m_Runtime;
    private List<IRuntimeActions> m_RuntimeActionsCallbackInterfaces = new List<IRuntimeActions>();
    private readonly InputAction m_Runtime_TestAudio;
    public struct RuntimeActions
    {
        private @PlayerInputs m_Wrapper;
        public RuntimeActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @TestAudio => m_Wrapper.m_Runtime_TestAudio;
        public InputActionMap Get() { return m_Wrapper.m_Runtime; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RuntimeActions set) { return set.Get(); }
        public void AddCallbacks(IRuntimeActions instance)
        {
            if (instance == null || m_Wrapper.m_RuntimeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RuntimeActionsCallbackInterfaces.Add(instance);
            @TestAudio.started += instance.OnTestAudio;
            @TestAudio.performed += instance.OnTestAudio;
            @TestAudio.canceled += instance.OnTestAudio;
        }

        private void UnregisterCallbacks(IRuntimeActions instance)
        {
            @TestAudio.started -= instance.OnTestAudio;
            @TestAudio.performed -= instance.OnTestAudio;
            @TestAudio.canceled -= instance.OnTestAudio;
        }

        public void RemoveCallbacks(IRuntimeActions instance)
        {
            if (m_Wrapper.m_RuntimeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRuntimeActions instance)
        {
            foreach (var item in m_Wrapper.m_RuntimeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RuntimeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RuntimeActions @Runtime => new RuntimeActions(this);
    public interface IRuntimeActions
    {
        void OnTestAudio(InputAction.CallbackContext context);
    }
}
